#created on: 30 oct. 2010
package cours

#list any import classes here.
import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import util.OutputDisplay;
#declare any global variables here
global OutputDisplay result;
rule "Credit rule"
	
	when
		$cash :CashFlow( $aDate : mvtDate, $no : accountNo ,type == CashFlow.CREDIT )
		$acc : Account(accountno ==$no  )
		$period : AccountingPeriod(  startDate <= $aDate && endDate >= $aDate)
	then 
		$acc.setBalance($acc.getBalance()+$cash.getAmount());
		result.showText("le compte no "+$no+ " a maintenant une valeur de "+$acc.getBalance());
end
rule "Debit rule"
	
	when
		$cash :CashFlow( $aDate : mvtDate, $no : accountNo ,type == CashFlow.DEBIT )
		$acc : Account(accountno ==$no  )
		$period : AccountingPeriod(  startDate <= $aDate && endDate >= $aDate)
	then 
		$acc.setBalance($acc.getBalance()-$cash.getAmount());
		result.showText("le compte no "+$no+ " a maintenant une valeur de "+$acc.getBalance());
end

