#created on: 21 nov. 2010
package droolscours.loyalty

#list any import classes here.



#declare any global variables here

import util.MyDate;
import droolscours.loyalty.domains.Ticket;
import droolscours.loyalty.domains.TicketLine;
import droolscours.loyalty.domains.Ligneop;
import droolscours.loyalty.domains.Product;
dialect "MVEL" 
rule "Your First Rule"
	
	when
		#conditions
	then 
		#actions
		
end

rule "Your Second Rule"
	#include attributes such as "salience" here...
	when
		#conditions
	then 
		#actions
		
end
rule "createdateOpPampers"
	when
	then
	   MyDate t = new MyDate();
	   t.setUneDate1(DateHelper.getDate("2010-12-01"));
	   t.setUneDate1(DateHelper.getDate("2010-12-31"));
	   t.setUneOp("pampers");
	   insert(t);
end
rule "opPameprs"
	when
		MyDate(uneOp=="pampers",$d1:uneDate1,$d2:uneDate2)
		$t : Ticket(date >=$d1,date <=$d2)
		$l : TicketLine(ticketID==$t.Id)
		$p : Product(Id == $l.productID , name=="pampers")
	then
		$l.setOp(new LigneOC());
		$l.getOp().setMontantReduction(new Float($l.getLineTotal()*0.2));
		$l.getOp().setNomOP("opPameprs");
end

